title: Mi Blog sobre IA
description: > # continuar en la siguiente línea
  Este es mi espacio personal donde comparto mi viaje en el mundo de la IA.
baseurl: "/docs" # la base URL relativa al dominio, por ejemplo "/blog" si tu sitio está en "example.com/blog"
url: "https://jdiez-go.github.io" # el URL de tu sitio
twitter_username: Jdiez_go # Twitter 
github_username:  jdiez-go # Usuario de GitHub

theme: jekyll-theme-primer # Tema en uso

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

